#!/usr/bin/php
<?php
/**
 * Plugin Setup Script
 *
 * Copies the contents to a sepcified directory,
 * with all name placeholders taken care of.
 */
chdir( __DIR__ );

$plugin = array();

// Get the plugin name
$plugin['name'] = readline( 'What is your plugin called? ' );
if ( ! $plugin['name'] ) {
	die( "No plugin name provided.\n" );
}

// Get optional description/tags
$plugin['desc'] = readline( 'What does it do in a nutshell? ' );
$plugin['tags'] = readline( 'What should it be tagged as? ' );

// Guess the filename
$plugin['file'] = strtolower( preg_replace( '/[\W_]+/', '-', $plugin['name'] ) );

// Guess the Namespace
$plugin['ns'] = preg_replace( '/\W+/', '', $plugin['name'] );

// Guess the slug
$plugin['slug'] = strtoupper( $plugin['ns'] );

// Offer to override the filename
if ( $value = readline( "Override assumed directory/file name ({$plugin['file']})? " ) ) {
	$plugin['file'] = $value;
}

// Offer to override the namespace
if ( $value = readline( "Override assumed namespace ({$plugin['ns']})? " ) ) {
	$plugin['ns'] = $value;
}

// Offer to override the slug
if ( $value = readline( "Override assumed slug ({$plugin['slug']})? " ) ) {
	$plugin['slug'] = $value;
}

function rename_files( $dir ) {
	global $plugin;

	$files = scandir( $dir );
	foreach ( $files as $file ) {
		if ( substr( $file, 0, 1 ) == '.' || in_array( $file, array( 'build', 'README.md', 'LICENSE' ) ) ) {
			continue;
		}

		$path = "$dir/$file";
		$file = str_replace( 'pluginname', strtolower( $plugin['ns'] ), $file );

		if ( is_dir( $path ) ) {
			rename_files( $path );
		} else {
			$content = file_get_contents( $path );

			$content = str_replace( array(
				'[plugin name]',
				'[plugin description]',
				'[plugin tags]',
				'PluginName',
				'pluginname',
				'plugin-name',
				'PLUGINNAME',
			), array(
				$plugin['name'],
				$plugin['desc'],
				$plugin['tags'],
				$plugin['ns'],
				strtolower( $plugin['ns'] ),
				$plugin['file'],
				$plugin['slug'],
			), $content );

			file_put_contents( $path, $content );

			rename( $path, "$dir/$file" );
		}
	}
}

rename_files( __DIR__ );
